# Generated by Django 4.1.1 on 2022-10-01 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djLC_app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='date_end',
            field=models.DateTimeField(verbose_name='%Y-%m-%d %H:%M'),
        ),
    ]
