# Generated by Django 4.1.1 on 2022-10-01 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djLC_app1', '0002_alter_history_date_end'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='djLC_app1.student', verbose_name='Ученик'),
        ),
    ]
