# Generated by Django 4.1.1 on 2022-10-01 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djLC_app1', '0003_history_student'),
    ]

    operations = [
        migrations.RenameField(
            model_name='history',
            old_name='type',
            new_name='type2',
        ),
    ]
