# Generated by Django 4.1.1 on 2022-10-03 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djLC_app1', '0005_history_evaluations2_alter_history_date_end'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='evaluations',
        ),
        migrations.RemoveField(
            model_name='student',
            name='evaluations2',
        ),
    ]
