# Generated by Django 4.1.1 on 2022-10-03 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djLC_app1', '0006_remove_student_evaluations_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='evaluations',
        ),
        migrations.AddField(
            model_name='history',
            name='evaluations1',
            field=models.IntegerField(default=1, verbose_name='Оценка по успеваемости'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='evaluations1',
            field=models.IntegerField(default=False, verbose_name='Оценка по успеваемости'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='evaluations2',
            field=models.IntegerField(default=12, verbose_name='Оценка по поведению'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='history',
            name='evaluations2',
            field=models.IntegerField(verbose_name='Оценка по поведению'),
        ),
    ]
