# Generated by Django 4.1.1 on 2022-10-03 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djLC_app1', '0007_remove_history_evaluations_history_evaluations1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='evaluations1',
            field=models.IntegerField(default=0, verbose_name='Оценка по успеваемости'),
        ),
        migrations.AlterField(
            model_name='student',
            name='evaluations2',
            field=models.IntegerField(default=0, verbose_name='Оценка по поведению'),
        ),
    ]
