# Generated by Django 4.1.1 on 2022-10-03 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djLC_app1', '0008_alter_student_evaluations1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='date_end',
            field=models.DateTimeField(verbose_name='Время окончания'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='date_beginning',
            field=models.DateTimeField(verbose_name='Время начало'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='date_end',
            field=models.DateTimeField(verbose_name='Время окончания'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='tutor',
            field=models.BooleanField(verbose_name='Куратор'),
        ),
    ]
