# Generated by Django 4.1.1 on 2022-10-03 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djLC_app1', '0009_alter_history_date_end_alter_schedule_date_beginning_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='text',
            field=models.TextField(verbose_name='текст(что делали на уроке или какие ни будь замечания'),
        ),
    ]
