# Generated by Django 4.1.1 on 2022-10-03 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djLC_app1', '0010_alter_history_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='evaluations1',
            field=models.IntegerField(verbose_name='Оценка по успеваемости(от 1 до 10)'),
        ),
        migrations.AlterField(
            model_name='history',
            name='evaluations2',
            field=models.IntegerField(verbose_name='Оценка по поведению(от 1 до 10)'),
        ),
    ]
