# Generated by Django 4.1.1 on 2022-10-05 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djLC_app1', '0013_alter_schedule_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='type',
        ),
    ]
